# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    robotic_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robotic_arm_controller:
  ros__parameters:
    joints:
      - base_waist_joint
      - waist_link1_joint
      - link1_link2_joint
      - link2_gripper_base_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity