<?xml version="1.0" ?>
<robot name="robotic_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(find robotic_arm_description)/urdf/materials.xacro" />
<xacro:include filename="$(find robotic_arm_description)/urdf/robotic_arm.trans" />
<xacro:include filename="$(find robotic_arm_description)/urdf/robotic_arm_gazebo.xacro"/>

<!-- Properties -->
<xacro:property name="PI" value="1.570796"/>
<!-- Constants for robot dimensions -->
<xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
<xacro:property name="width" value="0.01" /> <!-- Square dimensions (widthxwidth) of beams -->
<xacro:property name="height1" value="0.12" /> <!-- Link 1 -->
<xacro:property name="height2" value="1" /> <!-- Link 2 -->
<xacro:property name="height3" value="1" /> <!-- Link 3 -->
<xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->


<!-- Links -->
<link name = "world"/>

<link name="base_link">
  <inertial>
    <origin xyz="4.1292719567255465e-17 -0.1275 0.0075" rpy="0 0 0"/>
    <mass value="2.5408670074548567"/>
    <inertia ixx="0.033061" iyy="0.074955" izz="0.107921" ixy="-0.0" iyz="0.0" ixz="0.0"/>
  </inertial>
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://robotic_arm_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="oak"/>
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://robotic_arm_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="base">
  <inertial>
    <origin xyz="3.3070895591155684e-07 -0.06999939486232219 0.051365620594267386" rpy="0 0 0"/>
    <mass value="0.5102582987586253"/>
    <inertia ixx="0.001541" iyy="0.00162" izz="0.002267" ixy="0.0" iyz="0.0" ixz="0.0"/>
  </inertial>
  <visual>
    <origin xyz="-0.0 -0.07 -0.015" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://robotic_arm_description/meshes/base.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="pa_12_nylon_pa_603cf_with_eos_p_3d_printers"/>
  </visual>
  <collision>
    <origin xyz="-0.0 -0.07 -0.015" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://robotic_arm_description/meshes/base.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="waist">
  <inertial>
    <origin xyz="-0.013899791072812253 -0.003284120079222943 0.02372142968591144" rpy="0 0 0"/>
    <mass value="0.11734363935702768"/>
    <inertia ixx="8.6e-05" iyy="7.9e-05" izz="8.5e-05" ixy="-3e-06" iyz="1.1e-05" ixz="1.4e-05"/>
  </inertial>
  <visual>
    <origin xyz="0.0 0.0 -0.101" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://robotic_arm_description/meshes/waist.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="pa_12_nylon_pa_603cf_with_eos_p_3d_printers"/>
  </visual>
  <collision>
    <origin xyz="0.0 0.0 -0.101" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://robotic_arm_description/meshes/waist.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="link_1">
  <inertial>
    <origin xyz="0.007817729878361625 -4.0523557253042963e-07 0.06000021649587692" rpy="0 0 0"/>
    <mass value="0.07112302510728019"/>
    <inertia ixx="0.000121" iyy="0.000116" izz="1e-05" ixy="0.0" iyz="-0.0" ixz="0.0"/>
  </inertial>
  <visual>
    <origin xyz="0.001 0.014069 -0.141262" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://robotic_arm_description/meshes/link_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="pa_12_nylon_pa_603cf_with_eos_p_3d_printers"/>
  </visual>
  <collision>
    <origin xyz="0.001 0.014069 -0.141262" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://robotic_arm_description/meshes/link_1.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name="link_2">
  <inertial>
    <origin xyz="-0.01594540180295605 -0.046193837589282 4.672518474457821e-05" rpy="0 0 0"/>
    <mass value="0.11456681455688399"/>
    <inertia ixx="0.000224" iyy="2.7e-05" izz="0.00023" ixy="2.7e-05" iyz="0.0" ixz="-0.0"/>
  </inertial>
  <visual>
    <origin xyz="0.001 0.014069 -0.261262" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://robotic_arm_description/meshes/link_2.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="pa_12_nylon_pa_603cf_with_eos_p_3d_printers"/>
  </visual>
  <collision>
    <origin xyz="0.001 0.014069 -0.261262" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://robotic_arm_description/meshes/link_2.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
</link>

<link name ="link_3" >
  <visual>
    <origin xyz="0 0 ${-(height1/2)}" rpy="0 0 0"/>
    <geometry>
      <box size="${width} ${width} ${height1}"/>
    </geometry>
  </visual>
</link>

<link name = "tool_0">
</link>


<joint name = "virtual_joint" type= "fixed">
  <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
  <parent link="world"/>
  <child link="base_link"/>
</joint>

<joint name="rigid_1" type="fixed">
  <origin xyz="0.0 0.07 0.015" rpy="0 0 0"/>
  <parent link="base_link"/>
  <child link="base"/>
</joint>

<joint name="base_waist_joint" type="revolute">
  <origin xyz="-0.0 -0.07 0.086" rpy="0 0 0"/>
  <parent link="base"/>
  <child link="waist"/>
  <axis xyz="0.0 0.0 1.0"/>
  <dynamics damping="10.0" friction="2.0"/>
  <limit upper="3.14" lower="-3.14" effort="100" velocity="100"/>
</joint>

<joint name="waist_link1_joint" type="revolute">
  <origin xyz="-0.001 -0.014069 0.040262" rpy="0 0 0"/>
  <parent link="waist"/>
  <child link="link_1"/>
  <axis xyz="1.0 0.0 -0.0"/>
  <dynamics damping="10.0" friction="2.0"/>
  <limit upper="3.14" lower="-3.14" effort="100" velocity="100"/>
</joint>

<joint name="link1_link2_joint" type="revolute">
  <origin xyz="0.0 0.0 0.12" rpy="0 0 0"/>
  <parent link="link_1"/>
  <child link="link_2"/>
  <axis xyz="-1.0 0.0 -0.0"/>
  <dynamics damping="10.0" friction="2.0"/>
  <limit upper="3.14" lower="-3.14" effort="100" velocity="100"/>
</joint>

<joint name="link2_link3_joint" type="revolute">
  <origin xyz="0.002 -0.12 0.0" rpy="-1.57 0 0"/>
  <parent link="link_2"/>
  <child link="link_3"/>
  <axis xyz="1.0 0.0 0.0"/>
  <dynamics damping="10.0" friction="2.0"/>
  <limit upper="3.14" lower="-3.14" effort="100" velocity="100"/>
</joint>

<joint name="tool_joint" type="fixed">
  <origin xyz="0 0 ${-height1}" rpy="0 0 0" />
  <parent link="link_3"/>
  <child link="tool_0" />
</joint>


</robot>
